---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesomesystem-weight-deployment
  namespace: test
  labels:
    app: awesomesystem-weight
spec:
  selector:
    matchLabels:
      app: awesomesystem-weight
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: awesomesystem-weight
    spec:
      containers:
        - image: jailge/awesomesystem-weight:1.0.0
          name: awesomesystem-weight
          imagePullPolicy: Always
#          command: ["./main","-v","v1.3"]
          ports:
            - containerPort: 8877
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: awesomesystem-weight-service
  namespace: test
  labels:
    app: awesomesystem-weight
spec:
  selector:
    app: awesomesystem-weight
  ports:
    - name: awesomesystem-weight-port
      protocol: TCP
      port: 8877
      targetPort: 8877
      nodePort: 31877
  type: NodePort