---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesomesystem-weight-deployment
  namespace: uat
  labels:
    app: awesomesystem-weight
spec:
  selector:
    matchLabels:
      app: awesomesystem-weight
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: awesomesystem-weight
    spec:
      containers:
        - image: jailge/awesomesystem-weight:1.1.1
          name: awesomesystem-weight
          imagePullPolicy: Always
#          command: ["./main","-v","v1.3"]
          ports:
            - containerPort: 8877
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: awesomesystem-weight-service
  namespace: uat
  labels:
    app: awesomesystem-weight
spec:
  selector:
    app: awesomesystem-weight
  ports:
    - name: awesomesystem-weight-port
      protocol: TCP
      port: 8877
      targetPort: 8877
      nodePort: 30877
  type: NodePort